### ISSUE TITLE
是不是加入系统服务启动后，手动不能再运行了 ？armbian

### ISSUE THREAD

**Issue by xy928** [yzy613/ddns-watchdog#16]

**Comment by yzy613** [comment]
可以手动启动啊

**Comment by xy928** [comment]
root@aml:~/aliyun# ./ddns-watchdog-client
^C
root@aml:~/aliyun# systemctl status ddns-watchdog-client.service 
* ddns-watchdog-client.service - ddns-watchdog-client Service
   Loaded: loaded (/etc/systemd/system/ddns-watchdog-client.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-01-22 22:16:00 CST; 8min ago
 Main PID: 4749 (ddns-watchdog-c)
    Tasks: 7 (limit: 4915)
   Memory: 6.8M
      CPU: 1.191s
   CGroup: /system.slice/ddns-watchdog-client.service
           `-4749 /root/aliyun/ddns-watchdog-client -conf_path /root/aliyun/conf/

Jan 22 22:16:00 aml systemd[1]: Started ddns-watchdog-client Service.
root@aml:~/aliyun# ./ddns-watchdog-client 
^C
root@aml:~/aliyun# 
我不会发图。。。

**Comment by yzy613** [comment]
你的配置文件应该设置了 `check_cycle` ，设置了检测周期程序会常驻，不会自己退出

**Comment by xy928** [comment]
是检测到ip没改变就不会更新吗

**Comment by yzy613** [comment]
是的

**Comment by xy928** [comment]
所有手动运行不会有输出  ，也不会退出

**Comment by yzy613** [comment]
检测到 ip 变化才会有输出

**Comment by xy928** [comment]
懂了，谢谢 ，但是软件也不会退出，一直停在那里

**Comment by yzy613** [comment]
常驻嘛，systemctl 要求要这样运行才行

**Comment by yzy613** [comment]
还有问题需要解决吗？

**Comment by xy928** [comment]
没了  ，多谢  很好用
