### ISSUE TITLE
ipv6不能使用

### ISSUE THREAD

**Issue by MCSCDWIL** [yzy613/ddns-watchdog#18]
如图
![image](https://user-images.githubusercontent.com/53594566/125155692-337a6200-e194-11eb-868a-061116b6c5b7.png)

**Comment by yzy613** [comment]
忘了把服务端加卡机自启了，现在修好了

**Comment by yzy613** [comment]
闪电般的处理速度hhh

**Comment by MCSCDWIL** [comment]
好的
