### ISSUE TITLE
执行-f命令报错

### ISSUE THREAD

**Issue by 1379441534** [yzy613/ddns-watchdog#22]
![image](https://user-images.githubusercontent.com/34909204/141672076-42867ec1-fa43-4aea-bc25-8b753da264c8.png)

**Comment by yzy613** [comment]
这是阿里云dns连接超时了

**Comment by 1379441534** [comment]
DNS的问题，里面有个ipv6的dns，可能阿里那边解析到ipv6，然后网络不可达。

**Comment by yzy613** [comment]
好的，问题解决了就行 : )
