### ISSUE TITLE
请求支持华为云DNS

### ISSUE THREAD

**Issue by 1eb** [yzy613/ddns-watchdog#25]
请求支持[华为云DNS](https://www.huaweicloud.com/intl/zh-cn/product/dns.html)

PS：华为云国际版无需实名即可使用DNS解析，功能丰富且完全免费，TTL最低支持1秒

附：

- [API文档](https://support.huaweicloud.com/intl/zh-cn/api-dns/zh-cn_topic_0132421999.html)

**Comment by yzy613** [comment]
好的，我去了解一下。国际版和国内版是通用的吗？

**Comment by 1eb** [comment]
> 好的，我去了解一下。国际版和国内版是通用的吗？

应该是的，我看国内/国际的endpoint同一节点都是一样的

[国际版Endpoint](https://developer.huaweicloud.com/intl/zh-cn/endpoint?DNS)

[国内版Endpoint](https://developer.huaweicloud.com/endpoint?DNS)

**Comment by yzy613** [comment]
忘了说了，周末开发。还是大学牲，这几周网课还有在线考试。谢谢理解

**Comment by yzy613** [comment]
更新了更新了更新了
支持了支持了支持了
