### ISSUE TITLE
Cloudflare更改解析开盾问题

### ISSUE THREAD

**Issue by xiaoeyv** [yzy613/ddns-watchdog#27]
能否在cf配置文件内增加选项，内容为更换解析后是否开盾

**Comment by yzy613** [comment]
现在经过api更新的记录能开盾了？

**Comment by yzy613** [comment]
[feat: support cloudflare proxied](https://github.com/yzy613/ddns-watchdog/commit/cb140ff5c275c13ccfb04db5f555047bae054520)

**Comment by yzy613** [comment]
如果在24小时之后没有继续跟进该issue，那么该issue将会被close

**Comment by xiaoeyv** [comment]
是的，在body内加入bool类型的数值即可，如图
![image](https://github.com/yzy613/ddns-watchdog/assets/82286900/b81be150-6e6e-40e7-a7c7-07bb7c803d7e)
链接：https://developers.cloudflare.com/api/operations/dns-records-for-a-zone-update-dns-record

**Comment by xiaoeyv** [comment]
非常感谢！

**Comment by yzy613** [comment]
> 非常感谢！

没事儿，你要的功能已经发布在v1.5.5版本了
