### ISSUE TITLE
解析记录不存在

### ISSUE THREAD

**Issue by BrandonStudio** [yzy613/ddns-watchdog#28]
使用 Cloudflare 报错：
```
解析记录不存在
```

这个DDNS的意义不就在于添加DNS记录并实时更新吗？

**Comment by yzy613** [comment]
因为遵循了最小权限原则，原则上不会新建解析记录，只会在原有的记录上修改值。

**Comment by yzy613** [comment]
没问题我就关闭这个issue咯？

**Comment by yzy613** [comment]
> 创建记录和修改记录所需的权限都是写入

那你在dns解析那儿新建一个解析记录不就解决了嘛

**Comment by yzy613** [comment]
> 现有的ddns服务都是建立或修改
> 即使你在使用系统的时候
> ```bash
> echo powerful > show.txt
> ```
> 也是创建或修改
> 在编程语言中
> ```c
> fopen("/path/to/file", "w");
> ```
> 也是创建或修改
> 
> DDNS的意义在于免除手动更新的麻烦。在创建时当然可以手动添加纪录，但是之后更新时也都可以手动更新。不希望手动创建的想法与不希望手动更新的想法应该是一致的。

那是不是可以通过修改配置文件就可以创建一堆解析记录，只管建不管删。换一个说法，当你写错了子域名，你用你预想的那个域名连，死活连不上，因为错的域名创建成功了，如果不排查配置文件，你就不会知道写错了。

**Comment by yzy613** [comment]
我们都明确了立场，继续争论是没有意义的。我赞同每个人都可以持有不同的观点，但是我坚持我的观点。但是如果你提交了PR并且通过了review，那我将毫不犹豫的merge你的PR。
