### ISSUE TITLE
域名服务商

### ISSUE THREAD

**Issue by WuJIAN-0109** [yzy613/ddns-watchdog#29]
大佬可以添加一个花生壳的服务商吗？

**Comment by yzy613** [comment]
域名服务商任意一个都行啊，只是要对接dns服务商。况且花生壳有自己的ddns服务吧

**Comment by WuJIAN-0109** [comment]
抱歉大佬域名这些东西我也是刚接了解了一下不太清楚。自己搞了个域名用tp路由器自带的ddns绑了一下，端口转发也配置了，想从外面用ipv6访问一下主机，死活连不上。后来看到人家用自己主机本地配置ddns服务想着能不能照着实现一下

**Comment by yzy613** [comment]
> 抱歉大佬域名这些东西我也是刚接了解了一下不太清楚。自己搞了个域名用tp路由器自带的ddns绑了一下，端口转发也配置了，想从外面用ipv6访问一下主机，死活连不上。后来看到人家用自己主机本地配置ddns服务想着能不能照着实现一下

可以照着实现的。你在Releases里面下载最新的稳定版二进制程序，按照README.md的教程，就能实现了。
