### ISSUE TITLE
使用cron

### ISSUE THREAD

**Issue by WuJIAN-0109** [yzy613/ddns-watchdog#30]
可不可以使用cron来定时检查呢？

**Comment by yzy613** [comment]
可以啊。你把 `client.json` 的 `"check_cycle_minutes": 0` 保持原样，就可以每次打开只运行一次并结束。

**Comment by WuJIAN-0109** [comment]
你的意思是用crontab是吧 我想着是挂在服务中让它自己定时运行哈哈 不过用crontab也行呢

**Comment by yzy613** [comment]
> 你的意思是用crontab是吧 我想着是挂在服务中让它自己定时运行哈哈 不过用crontab也行呢

你说的服务是systemd吗？如果是systemd，我这个是原生支持的

**Comment by WuJIAN-0109** [comment]
是systemd 我想让它每天凌晨2点执行这样  如果使用现在check_cycle_minutes我还得凌晨2点启动一下

**Comment by yzy613** [comment]
你让他循环检查不是更好吗，每天凌晨2点执行，那如果其他时间ip变化了就不能及时更新了
