### ISSUE TITLE
Cloudflarer如果是多个域名，并且是a+aaaa的话解析有问题

### ISSUE THREAD

**Issue by 4860575** [yzy613/ddns-watchdog#34]
配置文件如下：
{
  "zone_id": "在你域名页面的右下角有个区域 ID",
  "api_token": "在 https://dash.cloudflare.com/profile/api-tokens 获取",
  "domain": {
    "a": "A记录子域名1.example.com",
    "a": "A记录子域名2.example.com",
    "aaaa": "A记录子域名1.example.com",
    "aaaa": "AAAA记录子域名2.example.com"
  },
  "proxied": false
}
只会解析或更新“A记录子域名2”“AAAA记录子域名2”

**Comment by yzy613** [comment]
a（或者aaaa）只能设置一个，不能设置两个。如果需要支持两个，建议另一个域名cname到被ddns托管的那个域名上。
---
举个例子
```
a: v4.example.com
aaaa: v6.example.com
```
在域名控制台上给www.example.com设置cname到v4.example.com；blog.example.com设置cname到v6.example.com。
